sbdchd/squawk

- .kodiak.toml
https://kodiakhq.com/docs/recipes#the-favourite
> add: kodiak

- .github/workflows/main.yml
- s/fmt
- s/lint
- s/test
- src/main.rs
- src/parse.rs
- src/reporter.rs
- src/rules.rs
- src/snapshots/squawk__reporter__test_reporter__display_violations_tty.snap
> add: ci for building binaries, tests, and lints

- .github/workflows/main.yml
Wasn't using the actual name of the project in the release binaries,
whoops!
> fix(ci): naming of release artifacts

- README.md
> docs(readme): include ci badge, update dev, add blog post

- README.md
include releases page as install method & remove version from usage
as it's going to get get stale.
> update(docs): readme with install info

- README.md
- package.json
- src/main.rs
Also update the keywords in package.json
> update(docs): steps for releasing a new version 

- README.md
> docs(github bot): outline github bot setup

- src/github.rs
- src/main.rs
- src/reporter.rs
- src/subcommand.rs
This now means an improperly configured squawk will error.
Also update the comment to remove the owl emoji.
> fix(github): error level HTTP status codes not being errors

- README.md
- src/github.rs
- src/subcommand.rs
Instead we can fetch the bot name via the github api.
> cut(upload-to-github): SQUAWK_GITHUB_BOT_NAME env var

- README.md
- cli/Cargo.toml
- cli/src/reporter.rs
- github/Cargo.toml
- github/README.md
- linter/Cargo.toml
- linter/README.md
- parser/Cargo.toml
- parser/README.md
- s/publish
Change some doc URLs and add some READMEs to the dependency crates.
> update: Cargo.tomls for dependent crates

- cli/src/reporter.rs
- linter/src/lib.rs
- linter/src/rules/adding_field_with_default.rs
- linter/src/rules/adding_not_null_field.rs
- linter/src/rules/bad_drop_database.rs
- linter/src/rules/ban_char_field.rs
- linter/src/rules/changing_column_type.rs
- linter/src/rules/constraint_missing_not_valid.rs
- linter/src/rules/disallow_unique_constraint.rs
- linter/src/rules/prefer_robust_stmts.rs
- linter/src/rules/prefer_text_field.rs
- linter/src/rules/renaming_column.rs
- linter/src/rules/renaming_table.rs
- linter/src/rules/require_concurrent_index_creation.rs
- linter/src/violations.rs
- parser/src/ast.rs
- parser/src/lib.rs
- parser/src/parse.rs
I'm not sure how CI passed previously, it didn't report any errors with
linting but opening another PR resulted in lint failures.
> fix(ci): clippy complaints for the 1.46.0 release

- cli/src/reporter.rs
```
echo 'ALTER TABLE "core_recipe" ALTER COLUMN "foo" SET DEFAULT 10;' | squawk --dump-ast=debug
```
```
[
RawStmt(
RawStmt {
stmt: AlterTableStmt(
AlterTableStmt {
cmds: [
AlterTableCmd(
AlterTableCmd {
subtype: ColumnDefault,
name: Some(
"foo",
),
def: Some(
Constant(
Object({
"location": Number(
57,
),
"val": Object({
"Integer": Object({
"ival": Number(
10,
),
}),
}),
}),
),
),
behavior: Restrict,
missing_ok: false,
},
),
],
relation: RangeVar(
RangeVar {
catalogname: None,
schemaname: None,
relname: "core_recipe",
inh: true,
relpersistence: "p",
alias: None,
location: 12,
},
),
relkind: Table,
missing_ok: false,
},
),
stmt_location: 0,
stmt_len: Some(
59,
),
},
),
]
```
> add: debug formatting option for --dump-ast

- linter/src/rules/adding_field_with_default.rs
- linter/src/rules/adding_foreign_key_constraint.rs
- linter/src/rules/adding_not_null_field.rs
- linter/src/rules/adding_primary_key_constraint.rs
- linter/src/rules/bad_drop_database.rs
- linter/src/rules/ban_char_field.rs
- linter/src/rules/changing_column_type.rs
- linter/src/rules/constraint_missing_not_valid.rs
- linter/src/rules/disallow_unique_constraint.rs
- linter/src/rules/prefer_robust_stmts.rs
- linter/src/rules/prefer_text_field.rs
- linter/src/rules/renaming_column.rs
- linter/src/rules/renaming_table.rs
- linter/src/rules/require_concurrent_index_creation.rs
- linter/src/violations.rs
- parser/src/ast.rs
This allows us to be more general in how we report errors with statements. I need this refactor for #97.
> ref RuleViolation to accept span

- docs/docusaurus.config.js
https://v2.docusaurus.io/docs/search
> add(doc): algolia search

- docs/docs/prefer-robust-stmts.md
Document what a robust statement looks like for indexes, columns, tables,
and constraints
fixes: https://github.com/sbdchd/squawk/issues/111
> update(docs): add more examples to prefer-robust-stmts

- CHANGELOG.md
- cli/src/reporter.rs
- cli/src/snapshots/squawk__reporter__test_reporter__display_violations_tty.snap
- docs/docs/rules-overview.md
Also add list of rules to Rules Overview to hopefully make it easier for users to find the rule they need.
> update CLI to link to website on lint errors

- CHANGELOG.md
- docs/docs/require-concurrent-index-creation.md
- linter/src/rules/prefer_robust_stmts.rs
- linter/src/rules/require_concurrent_index_creation.rs
- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__drop_extension.snap
- parser/src/snapshots/squawk_parser__parse__tests__drop_index.snap
> add drop index support to rules

- CHANGELOG.md
- cli/src/reporter.rs
- cli/src/snapshots/squawk__reporter__test_github_comment__generating_comment_multiple_files.snap
- cli/src/snapshots/squawk__reporter__test_github_comment__generating_comment_no_violations.snap
- cli/src/snapshots/squawk__reporter__test_github_comment__generating_no_violations_no_files.snap
- cli/src/subcommand.rs
- docs/docs/prefer-robust-stmts.md
> feat(github): include version number in comment body

- .github/workflows/main.yml
- cli/src/reporter.rs
- cli/src/subcommand.rs
- linter/src/errors.rs
- linter/src/lib.rs
- linter/src/violations.rs
- parser/src/error.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__create_procedure_stmt.snap
- parser/src/snapshots/squawk_parser__parse__tests__error_paths.snap
Also getting new errors from clippy, maybe we need to specifically pin
that as well?
> fix(ci): update toolchain to 1.51.0 match rust-toolchain file

- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_create_table_partition.snap
> fix(parse): create partition of table schema

- README.md
It took me a while to figure out how to do this, so I'm adding some more documentation.
> doc: npm publish steps

- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_alter_constraint_regression.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_create_table_regression.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_inh.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_sql_create_unique_index_safe.snap
- parser/src/snapshots/squawk_parser__parse__tests__parsing_create_table.snap
Location isn't always available
fixes #171
> fix(parser): parsing alter constraint

- .github/workflows/js.yml
- .github/workflows/rust.yml
We don't need to run the Rust CI when we make docs site changes.
> only run CI when necessary

- docs/docs/adding-field-with-default.md
- linter/src/lib.rs
- linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test_rules__adding_field_with_default.snap
- linter/src/rules/snapshots/squawk_linter__rules__adding_not_null_field__test_rules__adding_field_that_is_not_nullable.snap
> fix docs for adding-field-with-default

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- cli/src/reporter.rs
- package.json
The previous fix was incorrect and broke stdin
> actually fix silencing squawk stdin

- docs/docs/prefer-robust-stmts.md
> update(docs): link & syntax highlight

- .vscode/settings.json
- docs/docs/prefer-timestamptz.md
- docs/src/pages/index.js
- linter/src/lib.rs
- linter/src/rules/README.md
- linter/src/rules/changing_column_type.rs
- linter/src/rules/mod.rs
- linter/src/rules/prefer_text_field.rs
- linter/src/rules/prefer_timestamptz.rs
- linter/src/rules/snapshots/squawk_linter__rules__prefer_timestamptz__test_rules__alter_table.snap
- linter/src/rules/utils.rs
- linter/src/snapshots/squawk_linter__test_rules__rule_names_debug_snap.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_display_snap.snap
- linter/src/violations.rs
- parser/src/ast.rs
> add prefer-timestamptz

- docs/sidebars.js
- docs/src/pages/index.js
- linter/src/lib.rs
- linter/src/rules/README.md
- linter/src/rules/mod.rs
- linter/src/violations.rs
- plopfile.js
- s/new-rule
- templates/new_rule.md.template
- templates/new_rule.rs.template
- tsconfig.json
I looked on [Sourcegraph for plopfile.js](https://sourcegraph.com/search?q=context:global+repo:github.com+file:plopfile.js&patternType=literal) and found this [next.js plopfile.js](https://github.com/vercel/next.js/blob/7280c3ced186bb9a7ae3d7012613ef93f20b0fa9/plopfile.js) as an example.
[Plop](https://plopjs.com) works pretty well.
> add plop to scaffold new rules

- docs/docs/require-concurrent-index-deletion.md
I also wanted to show what it would look like with a specific schema
> fix examples in require-concurrent-index-deletion

- linter/src/rules/prefer_robust_stmts.rs
PostgreSQL only has a handful of DROP statements that may not be executed in a transaction. These include DROP DATABASE, DROP TABLESPACE, and sometimes DROP SUBSCRIPTION, according to my reading of the manual. These variants are parsed to different enum values in the AST and won't fall under `DropStmt` here.
Otherwise, DROP statements are allowed in transactions and can be rolled back with the transaction, leaving the database unchanged. This robustness-checking rule should not flag DROP statements in a transaction. Add new test cases to ensure this behavior as well.
> Recognize most DROP statements within a transaction as robust

- CHANGELOG.md
- cli/Cargo.toml
- flake.nix
- package.json
> release 0.21.0

- CHANGELOG.md
- cli/src/main.rs
- cli/src/reporter.rs
> Only read from stdin when no file paths are provided

- .github/workflows/js.yml
- .github/workflows/rust.yml
We need to run on pull_request to support fork PRs
> fix CI to run on pull request

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- flake.nix
- package.json
- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_alter_table_set_list.snap
> fix `alter table set`

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- flake.nix
- package.json
- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__alter_database_collation.snap
> fix alter database collation

- Cargo.toml
We need debug symbols to debug a program!
> fix debugging not working

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- cli/src/file_finding.rs
- cli/src/main.rs
- cli/src/reporter.rs
- cli/src/subcommand.rs
- docs/docs/cli.md
- flake.nix
- package.json
We can now find files via glob matching.
```
squawk 'migrations/*.sql'
```
> glob match in file finding

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- cli/src/config.rs
- cli/src/main.rs
- cli/src/snapshots/squawk__config__test_config__load_cfg_full.snap
- cli/src/snapshots/squawk__config__test_config__load_excluded_paths.snap
- cli/src/snapshots/squawk__config__test_config__load_excluded_rules.snap
- cli/src/snapshots/squawk__config__test_config__load_fail_on_violations.snap
- cli/src/snapshots/squawk__config__test_config__load_pg_version.snap
- cli/src/subcommand.rs
- docs/docs/cli.md
- flake.nix
- package.json
- support configuration for fail_on_violations
- support parent flags in upload-to-github command
> support more options in upload-to-github subcommand

- Cargo.lock
- parser/Cargo.toml
allows parsing things like:
```sql
select and
```
> parser: bump lib_pg parser dep to postgres 16

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- flake.nix
- package.json
- parser/Cargo.toml
> add back LIBPG_QUERY_PATH support

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- flake.nix
- package.json
Names need to be unique for the new GitHub upload action
> fix workflow

- Cargo.lock
- Cargo.toml
- crates/cli/src/reporter.rs
- crates/cli/src/snapshots/squawk__reporter__test_check_files__check_files_invalid_syntax.snap
- crates/linter/src/lib.rs
Getting ready to merge v2, part 2/?
Follow up to https://github.com/sbdchd/squawk/pull/429
> internal: bump dep versions

- Cargo.lock
- Cargo.toml
- crates/squawk_cli/Cargo.toml
- crates/squawk_cli/src/main.rs
> v2: add cli

- PLAN.md
- README.md
copy over and cleanup the plan from v2 implementation 
closes: https://github.com/sbdchd/squawk/issues/492
> docs: add PLAN.md

- .github/workflows/rust.yml
rel: https://github.com/sbdchd/squawk/issues/333#issuecomment-3027347982
> internal: publish cli to crates.io in ci

- CHANGELOG.md
- Cargo.lock
- crates/squawk/Cargo.toml
- flake.nix
- package.json
- squawk-vscode/package.json
rel: https://github.com/sbdchd/squawk/issues/597
> release: v2.21.1

- Cargo.lock
- Cargo.toml
- crates/squawk/Cargo.toml
- crates/squawk/src/main.rs
- crates/squawk_github/src/app.rs
- crates/xtask/Cargo.toml
rel: https://github.com/sbdchd/squawk/issues/629
> rust: bump http related deps & remove deprecated deps

- crates/squawk/src/main.rs
- crates/squawk_syntax/src/ast/generated/nodes.rs
- crates/squawk_syntax/src/ast/node_ext.rs
- crates/xtask/src/codegen.rs
> squawk_syntax: fix ast::BinExpr

- .github/workflows/rust.yml
rel: https://github.com/sbdchd/squawk/issues/333#issuecomment-3314972239
> ci: setup workflow to publish crates to crates.io
