- README.md
due to libpg_query squawk only supports Linux and macOS
> update(docs): readme with mention of platform support

- src/reporter.rs
- src/snapshots/squawk__reporter__test_reporter__display_violations_tty.snap
- src/snapshots/squawk__reporter__test_reporter__span_offsets.snap
We weren't slicing the SQL for the pretty errors correctly resulting in
the first char being cut off in some cases.
> fix: slicing of SQL for tty error reporting

- src/main.rs
Printing nothing when no paths, options, or stdin were provided wasn't a
great experience.
> add: print help when nothing specified

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/reporter.rs
- src/rules.rs
- src/snapshots/squawk__rules__test_rules__adding_index_non_concurrently.snap
Previously stdin wasn't detected and was assumed when `-` was used as
a path.
Now we use atty to check.
> ref: stdin to be automatically detected instead of using `-` as path

- .eslintignore
- .eslintrc.js
- .github/workflows/main.yml
- .prettierignore
- js/install.js
- package.json
- s/eslint
- s/prettier
- s/tsc
- yarn.lock
Ensure we run typescript, eslint, and prettier against the js install
scripts used in the npm install method.
> add(CI): eslint, prettier, typescript for npm related install scripts

- .gitignore
- Cargo.lock
- Cargo.toml
- src/github.rs
- src/main.rs
- src/reporter.rs
- src/snapshots/squawk__reporter__test_reporter__span_offsets.snap
- src/subcommand.rs
Comment on Pull Requests with a comment containing SQL and the errors `squawk` reports.
Could be paired with django migrations where a script runs [`sqlmigrate`](https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-sqlmigrate) to create `.sql` files for each migration.
Then `squawk` runs over all those files and leaves a comment on the specified PR.
Subsequent runs of `squawk` will update the existing comment. 
example: https://github.com/sbdchd/squawk/pull/14#issuecomment-647009446
> add: commenting on github pull requests w/ sql & errors

- src/github.rs
- src/subcommand.rs
Getting the bot id was pretty manually, instead we can use the bot name
instead.
> update(bot): subcommand to use bot name instead of id

- Cargo.lock
- Cargo.toml
- src/github.rs
- src/subcommand.rs
Also add new option for passing the github private key as base64 which
makes adding it to CI a bit easier.
minor styling changes to mapping errors into the respective types.
> ref(upload-to-github): prefix env vars with SQUAWK_

- src/main.rs
- src/reporter.rs
- src/snapshots/squawk__reporter__test_reporter__display_no_violations_tty.snap
Instead of staying silent squawk now outputs:
```
Found 0 issues in 1 file 🎉
```
Should help avoid the question of, did it actually check the files
> add(cli): output a success message for tty reporter

- src/main.rs
- src/reporter.rs
- src/subcommand.rs
When wrapping squawk it can be easier to use stdin. Instead of only
using `stdin` as the filename this extra argument allows users to specify
a name to use in the error reporting.
> add(cli): --stdin-filepath argument

- Cargo.lock
- Cargo.toml
- src/github.rs
- src/main.rs
- src/reporter.rs
- src/subcommand.rs
upload-to-github makes a few http requests to github which take a few
seconds.
Also log out the files we check.
Enabled via the new `--verbose` flag
> add: logging, mainly around upload-to-github

- src/subcommand.rs
Don't comment on PRs when there aren't any files checked.
> fix(upload-to-github): don't comment when no files

- README.md
- cli/src/reporter.rs
- linter/src/rules.rs
- parser/src/ast.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_replica_identity_stmt.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_sql_create_unique_index_safe.snap
Add a rule to suggest making statements not wrapped in transactions more robust with guards like `IF NOT EXISTS`
> add(rule): prefer-robust-stmts

- Cargo.lock
- cli/Cargo.toml
- github/Cargo.toml
- linter/Cargo.toml
- parser/Cargo.toml
Turns out every dependency crate needs to be up on crates.io for the top
level crate, the cli, to be publish.
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies
> release: v0.2.3 part 2, the cargo troubles

- github/Cargo.toml
- linter/Cargo.toml
- parser/Cargo.toml
The dep crates require metadata in their Cargo.tomls for crates.io to
accept them.
We need to publish all these crates to be able to publish the cli.
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies
> update: deps crate cargo tomls

- cli/src/reporter.rs
Remove the `<detail/>`, remove some extra headers, a couple links, an indent.
Minor changes all around that should make each migration more obviously
separate.
example: https://github.com/recipeyak/recipeyak/pull/575#issuecomment-656883411
> update(bot): comment body content

- README.md
- linter/src/lib.rs
- linter/src/rules/ban_char_field.rs
- linter/src/rules/mod.rs
- linter/src/rules/snapshots/squawk_linter__rules__ban_char_field__test_rules__creating_table_with_char_errors.snap
- linter/src/rules/snapshots/squawk_linter__rules__ban_char_field__test_rules__creating_table_with_var_char_and_text_okay.snap
- linter/src/violations.rs
`text` or `varchar` should be used instead of `character` aka `char`.
https://www.postgresql.org/docs/10/datatype-character.html
fixes: https://github.com/sbdchd/squawk/issues/50
> add(rule): ban-char-field, warn against using the character data type

- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_func_call.snap
Handle parsing function calls in alter table definition.
Probably should have an `other` case for most of these enums but not
super easy with serde: https://github.com/serde-rs/serde/issues/912
fixes: https://github.com/sbdchd/squawk/issues/55
> fix(parser): function calls in SQL

- .github/workflows/main.yml
- Cargo.lock
- cli/src/reporter.rs
Previous we used the generic "stable" toolchain so if a new version of
stable was released w/ updates the clippy our CI could fail on the next
run.
Now we pin to a specific version so we don't get any surprises.
> fix(ci): pin toolchain version so we don't get surprising updates

- .github/workflows/main.yml
- Cargo.lock
- cli/src/main.rs
- cli/src/reporter.rs
- cli/src/subcommand.rs
- github/src/lib.rs
- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__adding_index_non_concurrently.snap
- parser/src/snapshots/squawk_parser__parse__tests__json_index_operator.snap
- parser/src/snapshots/squawk_parser__parse__tests__migration.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_sql_create_index.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_sql_create_index_concurrently.snap
- parser/src/snapshots/squawk_parser__parse__tests__parsing_create_table.snap
- s/lint
Turns out `name` is an Option and that `expr` can be a more complicated
object rather than just a string.
Previously we didn't have any tests that exercised the `expr` property.
I think the issues with clippy are related to: https://github.com/rust-lang/rust-clippy/issues/2604
fixes: https://github.com/sbdchd/squawk/issues/59
> fix(parser): json index operator with alter table

- linter/src/rules/prefer_text_field.rs
- linter/src/rules/snapshots/squawk_linter__rules__prefer_text_field__test_rules__adding_column_non_text.snap
Previously we were only checking table creation. Now we check both table
creation and column creation.
Moved a tiny bit of logic into a helper to save a couple lines of code.
Kind of shows the need for a proper visitor setup.
> fix(rules): prefer text field to also check column additions

- linter/src/rules/ban_char_field.rs
- linter/src/rules/prefer_text_field.rs
- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_create_table_regression.snap
Previously squawk assumed that a tableEtl could only be a column type.
Seems the doc comment in the PG source is incorrect:
https://github.com/postgres/postgres/blob/20d3fe9009ddbbbb3da3a2da298f922054b43f8c/src/include/nodes/parsenodes.h#L2075
rel: https://github.com/sbdchd/squawk/issues/70
> fix(parser): handle case where table etl is a constraint

- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_inh.snap
`inh` isn't always present on the `RangeVar` so we default it to `false`.
rel: https://github.com/sbdchd/squawk/issues/79
> fix(parser): handle `RangeVar` with missing `inh` field.

- README.md
added npm badge because that is where the latest versions of squawk are available. The crates.io version is no longer updated, so I've removed the badge and installation instructions.
> add npm badge and remove crates.io

- cli/src/main.rs
- cli/src/reporter.rs
- linter/src/errors.rs
- parser/src/error.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__create_procedure_stmt.snap
- parser/src/snapshots/squawk_parser__parse__tests__error_paths.snap
We use `Debug` formatting for errors which looks like junk and isn't that useful to end users. Implementing `Display` allows us to present nicer errors.
I deleted the `ParseError` struct because it didn't seem helpful.
`echo hello world | squawk`
Before
```
Err(
CheckSQL(
ParsingSQL(
PGParseError(
ParseError {
message: Some(
"syntax error at or near \"hello\"",
),
funcname: Some(
"scanner_yyerror",
),
filename: Some(
"scan.l",
),
lineno: 1121,
cursorpos: 1,
context: None,
},
),
),
),
)
```
After
```
Problem linting SQL files: Postgres failed to parse query
```
```
squawk << EOF
ALTER TABLE "table_name" ALTER COLUMN "column_name" SET DEFAULT false;
EOF
```
Before
```
Err(
CheckSQL(
ParsingSQL(
JsonParse(
"unknown variant `TypeCast`, expected one of `FuncCall`, `Constraint`, `ColumnDef`, …
```
> add: better error reporting

- cli/src/main.rs
- cli/src/reporter.rs
- cli/src/subcommand.rs
- github/src/lib.rs
- parser/src/error.rs
Missing private key
```
GithubPrivateKeyMissing
Upload to GitHub failed: Missing GitHub private key
```
bad private key
```
GithubError(
JsonWebTokenCreation(
Error(
InvalidKeyFormat,
),
),
)
Upload to GitHub failed: Could not create JWT: InvalidKeyFormat
```
API call error
```
GithubError(
HttpError(
Error(
Status(
404,
),
"https://api.github.com/app",
),
),
)
Upload to GitHub failed: Problem calling GitHub API: https://api.github.com/app: Client Error: 404 Not Found
```
Schema error
```
Problem linting SQL files: Squawk schema failed to parse Postgres response: unknown variant `FuncCall`, expected one of `Constraint`, `ColumnDef`, `A_Const`, `ReplicaIdentityStmt` at line 1 column 220
Problem linting SQL files: Squawk schema failed to parse Postgres response. This indicates a bug with …
```
> add: better error reporting part 2

- linter/src/lib.rs
- linter/src/rules/prefer_robust_stmts.rs
Not all operations support IF EXISTS and IF NOT EXISTS. So I added a little caveat, "if your statement supports it".
> add detail to robust stmts warning

- docs/docusaurus.config.js
I like the dark theme but it doesn't highlight keywords making:
```sql
ALTER TABLE table_name ADD CONSTRAINT field_name_constraint UNIQUE (field_name);
```
look boring on https://squawkhq.com/docs/disallowed-unique-constraint
Instead use a different prism theme which looks better for those cases.
Before:
After:
> ref(docs): use light theme that highlights keywords

- linter/src/rules/ban_drop_column.rs
- linter/src/rules/prefer_text_field.rs
We shouldn't warn about varchar without a length specified since it is
equivalent to text, which the docs outline:
> The notations varchar(n) and char(n) are aliases for
> character varying(n) and character(n), respectively. character without
> length specifier is equivalent to character(1). If character varying
> is used without length specifier, the type accepts strings of any
> size. The latter is a PostgreSQL extension.
https://www.postgresql.org/docs/current/datatype-character.html
rel: https://github.com/sbdchd/squawk/issues/137
> fix(prefer-text-field): allow varchar without a length

- cli/src/main.rs
- cli/src/reporter.rs
- cli/src/subcommand.rs
Previously, if the `exclude` flag was passed before the `upload-to-github`
subcommand, the excluded rules wouldn't actually be included.
Now we take those excluded rules into account, so
```
squawk --exclude=ban-drop-database upload-to-github
```
is the same as
```
squawk upload-to-github --exclude=ban-drop-database
```
rel: https://github.com/sbdchd/squawk/issues/141
> fix(cli/upload-to-github): combine top level exclude rules arg

- linter/src/rules/adding_not_null_field.rs
- linter/src/rules/snapshots/squawk_linter__rules__adding_not_null_field__test_rules__adding_field_that_is_not_nullable.snap
There is another rule that warns about the default in pg <11 that we
ignore here.
Should probably remove those pre pg-11 rules at some point.
rel: https://github.com/sbdchd/squawk/issues/136
> fix(rules): allowing adding not null column with default

- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__alter_column_default_with_function.snap
Running Squawk on the following SQL statement
`alter table if exists foo alter column created_at set default current_timestamp`,
errors out with
```
Problem linting SQL files: Squawk schema failed to parse Postgres response. This indicates a bug with Squawk. Please report this error to https://github.com/sbdchd/squawk. Schema error: unknown variant `SQLValueFunction`, expected one of `TypeCast`, `FuncCall`, `Constraint`, `ColumnDef`, `A_Const`, `ReplicaIdentityStmt` at line 1 column 267
```
This PR adds the alter table command definition `SQLValueFunction` to the parser.
> fix(parse): support SQLValueFunction

- Cargo.lock
- linter/src/rules/require_concurrent_index_creation.rs
We weren't checking what type of drop was happening, so any drop stmt that
wasn't marked concurrent was causing an error.
https://github.com/sbdchd/squawk/issues/151
https://github.com/sbdchd/squawk/issues/152
https://github.com/sbdchd/squawk/issues/156
> fix(rules): require concurrent index creation

- Cargo.lock
- README.md
- cli/Cargo.toml
- github/Cargo.toml
- linter/Cargo.toml
- package.json
- parser/Cargo.toml
For some reason ran into https://github.com/rust-lang/rust/issues/65721 and https://github.com/rust-lang/rust/issues/49146 along with some other misc compiler errors and lints
Feels like every time I come back to this project the rust versions get out of wack
> release: 0.8.0

- foo.sql
- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__adding_index_non_concurrently.snap
- parser/src/snapshots/squawk_parser__parse__tests__create_index_without_index_name.snap
- parser/src/snapshots/squawk_parser__parse__tests__json_index_operator.snap
- parser/src/snapshots/squawk_parser__parse__tests__migration.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_sql_create_index.snap
- parser/src/snapshots/squawk_parser__parse__tests__parsing_create_table.snap
We don't actually use this field in the AST so we could remove it, but
might as well keep it around for later.
related: https://github.com/sbdchd/squawk/issues/167
> fix(parser): parsing create index with no name

- linter/src/rules/ban_drop_column.rs
- linter/src/rules/snapshots/squawk_linter__rules__renaming_table__test_rules__renaming_table.snap
This rule copied some of rename-table by mistake, which was causing
issues in https://github.com/sbdchd/squawk/issues/166
> fix(ban-drop-column): copy pasta of rename-table row issue

- docs/README.md
- docs/docusaurus.config.js
- docs/package.json
Algolia's removing the old doc search in three months, so we need to bump this.
> upgrade docsearch to support continued indexing

- .github/workflows/main.yml
We need to enable builds on "pull_request" for GitHub to display a button to allow CI for non-members
> enable GitHub UI button to allow CI to run for outside contributors

- docs/src/pages/index.js
> docs: add padding below features

- .pre-commit-hooks.yaml
- README.md
Adds the ability to use Squawk with `pre-commit` (https://pre-commit.com/). I tried referencing this in a local project and it worked. Happy to provide any additional context that might be useful.
> pre-commit hook

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- github/src/app.rs
- github/src/lib.rs
- package.json
Our slug name was incorrect for GitHub Actions authentication, so duplicate messages were being written.
> fix actions auth creating duplicate messages

- Cargo.lock
- README.md
- cli/Cargo.toml
- cli/src/config.rs
- cli/src/main.rs
- cli/src/reporter.rs
- docs/docs/cli.md
Hello folks 👋 
This PR adds support for the configuration file as proposed https://github.com/sbdchd/squawk/issues/205
As discussed in the issue It prioritizes the CLI flag before it starts using the config file, I've also added a CLI flag to specify a custom configuration path (`-c` or `--config`).
The file name is `.squawk.toml` and if a custom path it's not specified or the file specified doesn't exist then it tries to look for the file in the following paths with this priority:
1.  `./.squawk.toml`
2. ~~`$GIT_REPO_ROOT/.squawk.toml`~~ -> Now it traverses back directories up to a depth of 5
3. `~/.squawk.toml`
If not found on any of these paths then the program continues running without a config file.
These changes have been tested only on macOS, it would be great if someone wants to …
> Add support for configuration file

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- linter/Cargo.toml
- linter/src/lib.rs
- linter/src/snapshots/squawk_linter__test_rules__rule_names_debug_snap.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_display_snap.snap
- linter/src/violations.rs
- package.json
We can auto generate the IDs from our enum. We already use the auto generated IDs for parsing from the configuration file, so this makes everything consistent.
I ran into an issue where `fmt::Display` was being recursive which I fixed with 85f626acad0f27538c1c101a519d523e0b92bb74.
> use auto generated IDs

- docs/docs/prefer-robust-stmts.md
- linter/src/rules/prefer_robust_stmts.rs
- linter/src/rules/snapshots/squawk_linter__rules__prefer_robust_stmts__test_rules__create_index_concurrently_unnamed.snap
This is a problematic construct for the reasons described in
the changes to prefer-robust-stmts.md.
We learned this the hard way 🙃
> prefer-robust-statements: explicitly stop unnamed CREATE INDEX CONCURRENTLY

- Cargo.lock
- flake.nix
- parser/Cargo.toml
My changes to libpg_query-sys got into upstream with some slight differences (renaming the
environment variable mostly), and got published to crates.io, so we can
also just not have a git dep there anymore.
However, there was a dependency conflict due to the current pinned deps, so I
had to run cargo update. All works now and passes tests.
> cargo update, move libpg_query-sys to a crates.io dep

- linter/src/rules/adding_foreign_key_constraint.rs
Noticed a case that squeaks by this check.  There are so many ways to add a constraint in SQL 😄 
```sql
ALTER TABLE "emails" ADD COLUMN "user_id" INT REFERENCES "user" ("id");
```
> Check for add column using references

- linter/src/rules/prefer_robust_stmts.rs
> ignore single stmts with prefer-robust-stmts

- flake.nix
- s/update-version
Hello! I noticed when using the flake that the Nix default package version didn't match what `squawk --version` showed. I found that the version was out of date in `flake.nix` so I updated that and the `s/update-version` script so that it should be kept in sync for the future.
Awesome project, by the way!
> Fix flake version

- linter/src/rules/ban_char_field.rs
- linter/src/rules/constraint_missing_not_valid.rs
- linter/src/rules/snapshots/squawk_linter__rules__ban_char_field__test_rules__regression_with_indexing_2.snap
- we weren't clearing the set of okay constraint names when we entered a new transaction
- also there was an issue where we were constructing a span that had a length greater than the actual SQL. Fiddling with this was annoying so I scraped it and now we pick the last statement for reporting.
rel: https://github.com/sbdchd/squawk/issues/258
> fix(linter): indexing error & bug with constraint_missing_not_valid

- flake.nix
This was missing when using `nix develop`, and since it is used by `s/fmt`, I figured it should be added to provide a (more) complete development environment.
> Add rustfmt (cargo fmt) as a tool in the flake-provided dev shell

- Cargo.lock
I was noticing that Cargo.lock had unstaged changes in it when I built against a recent version of master. It looks like the version was bumped in 9afce6a for cli/Cargo.toml, but the lock file didn't get updated. I'm assuming this should be changed as well, but feel free to close if that's not the case.
> Update Cargo.lock to relect version update in 9afce6a

- flake.nix
I noticed this was also missing when addressing comments in #264, and since it is used by `s/lint`, I figured it should be added to provide a (more) complete development environment.
> Add Clippy as a tool in the flake-provided dev shell

- Cargo.lock
- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parsing_create_table_using_like.snap
Adds minimal support for `CREATE TABLE ... (LIKE ...)`, resolves #270
> Support TableLikeClause in table creation

- .gitignore
- Cargo.lock
- docs/docs/prefer-big-int.md
- docs/docs/prefer-bigint-over-int.md
- docs/docs/prefer-bigint-over-smallint.md
- docs/sidebars.js
- docs/src/pages/index.js
- linter/src/lib.rs
- linter/src/rules/mod.rs
- linter/src/rules/prefer_bigint_over_int.rs
- linter/src/rules/prefer_bigint_over_smallint.rs
- linter/src/rules/snapshots/squawk_linter__rules__prefer_bigint_over_int__test_rules__create_table_bad.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_bigint_over_smallint__test_rules__create_table_bad.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_debug_snap.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_display_snap.snap
- linter/src/violations.rs
Fixes #272
- mostly copy/paste to ensure `prefer-big-int` stays backwards compatible and easy to delete in a future release
> Split prefer-big-int into int and smallint

- parser/src/ast.rs
- parser/src/parse.rs
- parser/src/snapshots/squawk_parser__parse__tests__parse_attach_table_partition.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_detach_table_partition.snap
Adds minimal support for partition commands, partially resolves #279
> Support PartitionCmd in alter table statement

- Cargo.lock
- parser/src/parse.rs
`libpg_query::PgQueryError::message` [is declared](https://docs.rs/libpg_query-sys/0.2.1/libpg_query/struct.PgQueryError.html) as `c_char`, not `i8`. This causes error when building `squawk` on platforms where `c_char` is `u8`:
```
Compiling squawk-parser v0.0.0 (/src/origin/parser)
error[E0308]: mismatched types======>  ] 280/292: openssl-sys(build), squawk-parser
--> parser/src/parse.rs:12:38
|
12 |         unsafe { Some(CStr::from_ptr(str_ptr).to_string_lossy().into()) }
|                       -------------- ^^^^^^^ expected `u8`, found `i8`
|                       |
|                       arguments to this function are incorrect
|
= note: expected raw pointer `*const u8`
found raw pointer `*mut i8`
note: associated function defined here
--> …
```
> Fix c_char type

- flake.lock
- flake.nix
I tried building Squawk recently in the Nix development shell and was running into a `cargo build` issue due to an older rustc version coming from nixpkgs: "error[E0658]: `let...else` statements are unstable". I see that the rust-toolchain is now using 1.67.0 and nixpkgs is providing 1.61.0.
I ran `nix flake update` to get newer pinned versions of nixpkgs and the flake-utils library (not really important for this problem). I also had to override the version of libpg_query that comes through nixpkgs because it isn't compatible with Squawk. Upon making these changes, `nix develop` and `nix build` work correctly again.
> Update Nix flake with newer nixpkgs version

- docs/docs/ban-drop-not-null.md
- docs/sidebars.js
- docs/src/pages/index.js
- linter/src/lib.rs
- linter/src/rules/ban_drop_not_null.rs
- linter/src/rules/mod.rs
- linter/src/rules/snapshots/squawk_linter__rules__ban_drop_not_null__test_rules__ban_drop_not_null.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_debug_snap.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_display_snap.snap
- linter/src/violations.rs
This addresses #282 by creating a new rule that bans dropping NOT NULL constraints on columns. This can cause problems in application code that doesn't expect NULL values.
> Introduce a new rule that bans dropping NOT NULL constraints

- package.json
- yarn.lock
I've used `s/new-rule` a couple times and had failures due to missing the `plop` command on my system. I figured this could be added to the dev dependencies for this project so that we're using the same version and it's easier to contribute new rules.
> Add Plop to dev dependencies

- docs/docs/transaction-nesting.md
- docs/sidebars.js
- docs/src/pages/index.js
- linter/src/lib.rs
- linter/src/rules/mod.rs
- linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test_rules__begin_repeated.snap
- linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test_rules__begin_with_assume_in_transaction.snap
- linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test_rules__commit_repeated.snap
- linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test_rules__commit_with_assume_in_transaction.snap
- linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test_rules__rollback_with_assume_in_transaction.snap
- linter/src/rules/transaction_nesting.rs
- linter/src/snapshots/squawk_linter__test_rules__rule_names_debug_snap.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_display_snap.snap
- linter/src/violations.rs
Since PostgreSQL doesn't support true nested transactions, this rule looks for transaction managements statements that might cause problems when running migrations, like BEGIN or COMMIT being issued multiple times. It also enforces strictness around assume-in-transaction: the migration tool is in charge of the transaction and explicit BEGIN/COMMIT statements may cause problems.
> Introduce a new rule to lint nested transactions

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- cli/src/reporter.rs
- cli/src/subcommand.rs
- flake.nix
- package.json
This PR potentially fixes #326 and adds an option to fail on error when running `upload-to-github`.
Disclaimer: I'm not well versed in Rust, so feel free to suggest any modifications.
Also, if you don't agree with the solution for the problem itself, I don't mind closing this one and the issue.
Thank you!
> Add option to fail on error when running with upload-to-github

- cli/src/subcommand.rs
Now we display an error message when no enough required parameters are supplied:
```
Upload to GitHub failed: Missing GitHub credentials:
For a GitHub token:
--github-token is required
For a GitHub App:
--github-app-id is required
--github-install-id is required
--github-private-key or --github-private-key-base64 is required
```
> refactor app initialization

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- cli/src/subcommand.rs
- flake.nix
- package.json
Previously we would only add or update a comment if violations found. In cases where violations were resolved, this would leave stale warnings in comments.
Now we will always comment as long as files are found and checked.
There is a slight edge case where if a file is no longer in the pull request, the comment won't be updated.
related: #326
> Always comment when Squawk checks a file

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- docs/docs/ban-concurrent-index-creation-in-transaction.md
- docs/sidebars.js
- docs/src/pages/index.js
- flake.nix
- linter/src/lib.rs
- linter/src/rules/ban_concurrent_index_creation_in_transaction.rs
- linter/src/rules/mod.rs
- linter/src/rules/snapshots/squawk_linter__rules__ban_concurrent_index_creation_in_transaction__test_rules__adding_index_concurrently_in_transaction-2.snap
- linter/src/rules/snapshots/squawk_linter__rules__ban_concurrent_index_creation_in_transaction__test_rules__adding_index_concurrently_in_transaction.snap
- linter/src/rules/snapshots/squawk_linter__rules__ban_concurrent_index_creation_in_transaction__test_rules__adding_index_concurrently_in_transaction_with_assume_in_transaction-2.snap
- linter/src/rules/snapshots/squawk_linter__rules__ban_concurrent_index_creation_in_transaction__test_rules__adding_index_concurrently_in_transaction_with_assume_in_transaction.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_debug_snap.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_display_snap.snap
- linter/src/violations.rs
- package.json
Add a rule that warns about creating an index with the `CONCURRENTLY` option inside a transaction, since that's not allowed in Postgres. This will resolve https://github.com/sbdchd/squawk/issues/332
> Add rule to prevent concurrent index creation inside transactions

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- docs/docs/ban-concurrent-index-creation-in-transaction.md
- flake.nix
- linter/src/rules/ban_concurrent_index_creation_in_transaction.rs
- linter/src/rules/snapshots/squawk_linter__rules__ban_concurrent_index_creation_in_transaction__test_rules__adding_index_concurrently_in_transaction_with_assume_in_transaction.snap
- linter/src/rules/snapshots/squawk_linter__rules__ban_concurrent_index_creation_in_transaction__test_rules__adding_index_concurrently_in_transaction_with_assume_in_transaction_but_outside.snap
- package.json
This changes the logic of `ban-concurrent-index-creation-in-transaction` when `assume_in_transaction` is set. Tools like `golang-migrate` always wrap migrations in transactions but support individual statements like `CREATE INDEX CONCURRENTLY` by not wrapping them in transactions.
To support this, this commit alters the logic of `ban-concurrent-index-creation-in-transaction` to allow a standalone index create command even when `assume_in_transaction` is `true`.
> Issue-338: Adjust handling of ban-concurrent-index-creation-in-transaction

- CHANGELOG.md
- docs/docs/disallowed-unique-constraint.md
- linter/src/rules/disallow_unique_constraint.rs
- linter/src/rules/snapshots/squawk_linter__rules__disallow_unique_constraint__test_rules__unique_constraint_inline_add_column.snap
- linter/src/rules/snapshots/squawk_linter__rules__disallow_unique_constraint__test_rules__unique_constraint_inline_add_column_unique.snap
> improve unique constraint check

- docs/sidebars.js
Page for `ban-drop-column` [exists](https://squawkhq.com/docs/ban-drop-column/), but it is not listed in the sidebar, for easier access.
> docs(sidebar): add missing `ban-drop-column`

- Cargo.lock
- parser/Cargo.toml
This updates `bindgen` to 0.64, fixing https://github.com/rust-lang/rust-bindgen/issues/2312 (via [`libpg_query-sys`](https://crates.io/crates/libpg_query-sys/0.2.1)) when building from source.
> Update `bindgen` to 0.64

- docs/docs/prefer-identity.md
Addresses https://github.com/sbdchd/squawk/issues/346
This adds sqlalchemy docs for the prefer-identity rule now that `Identity` is supported as of sqlalchemy 1.4 per https://docs.sqlalchemy.org/en/20/core/defaults.html#identity-ddl
> Update sqlalchemy docs for prefer-identity rule

- CHANGELOG.md
- Cargo.lock
- README.md
- cli/Cargo.toml
- cli/src/config.rs
- cli/src/main.rs
- cli/src/reporter.rs
- cli/src/snapshots/squawk__config__test_config__load_cfg_full.snap
- cli/src/snapshots/squawk__config__test_config__load_excluded_paths.snap
- cli/src/snapshots/squawk__config__test_config__load_excluded_rules.snap
- cli/src/snapshots/squawk__config__test_config__load_pg_version.snap
- cli/src/subcommand.rs
- docs/docs/cli.md
- flake.nix
- package.json
Adding a CLI flag as well as a field in the config file for skipping paths using glob patterns.  This is useful for introducing the linter on an already live service which had linter warnings on previous migrations.
> feat: add a flag & config for skipping path glob patterns

- js/install.js
> fix: typo in supported platforms for `darwin-x64`

- .github/workflows/rust.yml
- CHANGELOG.md
- README.md
- js/install.js
#368
I tried to build the CLI on a Windows GitHub runner and it seems like there are no problems.
I tested the built binary on one of the Windows machines:
```bash
PS C:\Users\...\Downloads> .\squawk-windows-x64.exe --version
squawk 1.1.2
PS C:\Users\...\Downloads> .\squawk-windows-x64.exe 'test.sql'
test.sql:1:0: warning: adding-field-with-default
1 | ALTER TABLE foo ADD COLUMN bar TEXT NOT NULL DEFAULT "baz";
note: Adding a field with a VOLATILE DEFAULT requires a table rewrite with an ACCESS EXCLUSIVE lock. In Postgres versions 11+, non-VOLATILE DEFAULTs can be added without a rewrite.
help: Add the field as nullable, then set a default, backfill, and remove nullability.
find detailed examples and solutions for each rule at https://squawkhq.com/docs/rules
PS C:\Users\...\Downloads>
```
> Added windows support (#368)

- docs/docs/disallowed-unique-constraint.md
Fixes #366 
This updates the docs for `disallowed-unique-constraint` regarding creating constraints using an index.
> Fix docs for disallowed-unique-constraint

- .github/workflows/python.yml
If we remove this token, Maturin uses OIDC
https://github.com/PyO3/maturin/blob/1cd1140ca472a2ce8dac9a7f2b1cd16324af1adc/src/upload.rs#L216-L221
> fix python publish

- docs/docs/github_app.md
Fix mistake added in #381, where updating to `actions/checkout` past `v1` would mean the example stops working.
This is due to change in the checkout functionality in `actions/checkout` introduced in v2 (beta). See https://github.com/actions/checkout/blob/main/CHANGELOG.md#v2-beta
> fix: github_app.md

- linter/src/rules/ban_concurrent_index_creation_in_transaction.rs
- linter/src/rules/constraint_missing_not_valid.rs
- linter/src/rules/prefer_robust_stmts.rs
- linter/src/rules/utils.rs
Adds missing check for `TransactionStmtKind::Start` when verifying the existence of transactions as this is the same as using BEGIN: https://www.postgresql.org/docs/current/sql-begin.html
Fixes https://github.com/sbdchd/squawk/issues/385
> Fix issue #385

- .github/workflows/python.yml
- cli/src/reporter.rs
- linter/src/rules/ban_char_field.rs
- linter/src/rules/prefer_big_int.rs
- linter/src/rules/prefer_bigint_over_int.rs
- linter/src/rules/prefer_bigint_over_smallint.rs
- linter/src/rules/prefer_identity.rs
- linter/src/rules/prefer_text_field.rs
- linter/src/rules/prefer_timestamptz.rs
- linter/src/rules/snapshots/squawk_linter__rules__ban_char_field__test_rules__creating_table_with_char_errors.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_big_int__test_rules__create_table_bad.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_big_int__test_rules__create_table_many_errors.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_bigint_over_int__test_rules__create_table_bad.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_bigint_over_smallint__test_rules__create_table_bad.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_identity__test_rules__prefer_identity_bad.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_text_field__test_rules__adding_column_non_text.snap
- linter/src/rules/snapshots/squawk_linter__rules__prefer_timestamptz__test_rules__alter_table.snap
- parser/src/ast.rs
Fixed the display of lint errors for large DDL statements. Previously, when an error occurred, the output included the entire SQL statement, which could be very lengthy. The update now shows only the relevant line(s) with the issue.
For large DDL files, any linting errors resulted in the full SQL being displayed in the output, making it difficult to identify the exact problematic lines in lengthy scripts.
**Example File**:
```sql
create table test_table (
col1 varchar(255),
col2 varchar(255),
col3 varchar(255)
--- other columns
);
```
**Previous Output**
Before the change, the output included the full SQL statement, repeated for each warning:
```
.tmp/big-int.sql:1:0: warning: prefer-text-field
1 | create table test_table (
2 |     col1 varchar(255),
3 |     col2 varchar(255),
4 | …
```
> Use ColumnDef position in lint report

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- flake.nix
- package.json
> use ubuntu 22

- linter/src/rules/adding_field_with_default.rs
- linter/src/rules/ban_char_field.rs
- linter/src/rules/constraint_missing_not_valid.rs
- linter/src/rules/snapshots/squawk_linter__rules__constraint_missing_not_valid__test_rules__regression_with_indexing_2.snap
was put in the wrong file in https://github.com/sbdchd/squawk/commit/c3979a9e49c7b6caf4a6db89e887c171472bde68
> tests: move test to proper lint

- docs/docs/adding-field-with-default.md
- docs/docs/adding-not-nullable-field.md
- linter/src/rules/adding_not_null_field.rs
Hey there, I noticed in https://github.com/sbdchd/squawk/pull/301 that the logic for handling adding new fields as null was split out from [adding-not-nullable-field](https://squawkhq.com/docs/adding-not-nullable-field) into [adding-required-field](https://squawkhq.com/docs/adding-required-field).
The logic for performing the pg version check wasn't removed however, so this causes the rule to fail to detect changing existing columns to be not null. All the logic for checking not null for adding cols was extracted to `adding-required-field` or covered by `adding-required-field`, so I think we can remove the version check altogether.
https://github.com/sbdchd/squawk/pull/301 has nice examples showing how the other rules cover the adding column with not null. I've included the part below to …
> Ignore postgres version in adding-not-nullable-field

- docs/docs/ban-alter-domain-with-add-constraint.md
- docs/docs/ban-create-domain-with-constraint.md
- docs/sidebars.js
- docs/src/pages/index.js
- linter/src/lib.rs
- linter/src/rules/ban_alter_domain_with_add_constraint.rs
- linter/src/rules/ban_create_domain_with_constraint.rs
- linter/src/rules/mod.rs
- linter/src/rules/snapshots/squawk_linter__rules__ban_alter_domain_with_add_constraint__test_rules__ban_alter_domain_with_add_constraint_works.snap
- linter/src/rules/snapshots/squawk_linter__rules__ban_create_domain_with_constraint__test_rules__ban_create_domain_with_constraint_works.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_debug_snap.snap
- linter/src/snapshots/squawk_linter__test_rules__rule_names_display_snap.snap
- linter/src/violations.rs
- parser/src/ast.rs
- parser/src/snapshots/squawk_parser__parse__tests__create_domain_stmt.snap
- parser/src/snapshots/squawk_parser__parse__tests__parse_alter_domain_stmt.snap
Ban creating domains with constraints (`CREATE DOMAIN ... CHECK`) or adding constraints to existing domains (`ALTER DOMAIN ... ADD CONSTRAINT`).
Domains with constraints are hard to use/operationalize well with online migrations, have performance problems, and are soft-discourage by Postgres developers as having unfavorable tradeoffs.
> add rules to ban domains with constraints

- Dockerfile
Introduce a multi-stage Dockerfile for the Squawk project. 
The builder stage compiles the Rust application, while the final stage creates a lightweight container to run Squawk as a non-root user. This setup improves portability and simplifies deployment.
Refers to https://github.com/sbdchd/squawk/issues/290
> Add a Dockerfile to build and run Squawk

- CHANGELOG.md
- Cargo.lock
- cli/Cargo.toml
- cli/src/reporter.rs
- cli/src/snapshots/squawk__reporter__test_reporter__highlight_column_for_issues.snap
- cli/src/snapshots/squawk__reporter__test_reporter__span_offsets.snap
- flake.nix
- package.json
> fix panic when formatting violations

- Cargo.lock
- Cargo.toml
- crates/linter/Cargo.toml
- crates/squawk_lexer/Cargo.toml
- crates/squawk_lexer/README.md
- crates/squawk_lexer/src/LICENSE-MIT
- crates/squawk_lexer/src/cursor.rs
- crates/squawk_lexer/src/lib.rs
- crates/squawk_lexer/src/snapshots/lexer__tests__bitstring.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__block_comment.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__block_comment_unterminated.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__dollar_quote_mismatch_tags_complex.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__dollar_quote_mismatch_tags_simple.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__dollar_quoting.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__lex_statement.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__line_comment.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__line_comment_whitespace.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__numeric.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__numeric_non_decimal.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__numeric_with_seperators.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__params.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__quoted_ident.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__select_with_period.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__string.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__string_unicode_escape.snap
- crates/squawk_lexer/src/snapshots/lexer__tests__string_with_escapes.snap
- crates/squawk_lexer/src/token.rs
- s/lint
Part of the v2 implementation.
Going to prefix the crates with `squawk_` even though they aren't in the other repo. This should make it work with the existing crates which don't have a prefix.
> v2: add lexer

- Cargo.lock
- Cargo.toml
- crates/squawk_wasm/Cargo.toml
- crates/squawk_wasm/README.md
- crates/squawk_wasm/src/lib.rs
> v2: add wasm

- README.md
This commit updates the README to include an example of how to use the tool with Docker. It provides a clear command to run the container for checking SQL files without requiring installation.
> Add Docker usage example to README

- crates/squawk_parser/src/grammar.rs
- crates/squawk_parser/src/snapshots/squawk_parser__test__select_err.snap
- crates/squawk_parser/test_data/err/select.sql
previously we'd parse:
```sql
select t 1;
```
as a type cast, but this sort of type cast is only valid when we're using a string literal!
Now we're more restrictive
> parser: fix parsing string literal type cast

- README.md
- crates/squawk_linter/src/rules/constraint_missing_not_valid.rs
- crates/squawk_linter/src/rules/disallow_unique_constraint.rs
- crates/squawk_linter/src/rules/prefer_identity.rs
- crates/squawk_linter/src/rules/prefer_text_field.rs
- crates/squawk_linter/src/rules/require_concurrent_index_creation.rs
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__constraint_missing_not_valid__test__adding_check_constraint_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__constraint_missing_not_valid__test__adding_fk_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__disallow_unique_constraint__test__adding_unique_constraint_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__disallow_unique_constraint__test__unique_constraint_inline_add_column_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__disallow_unique_constraint__test__unique_constraint_inline_add_column_unique_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_identity__test__err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_text_field__test__adding_column_non_text_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_text_field__test__create_table_with_pgcatalog_varchar_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_text_field__test__create_table_with_varchar_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_text_field__test__increase_varchar_size_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__require_concurrent_index_creation__test__adding_index_non_concurrently_err.snap
Trying to make the rule copy more consistent, but will need to go through in the future and figure out a proper style guide for it.
Also updated the readme example with the new annotate-snippets powered tty output!
> docs: update readme example output & adjust rule copy

- README.md
- docs/docs/cli.md
With v2 we can ignore errors via the `squawk-ignore` comment.
> docs: add notes about ignoring errors via comment

- .vscode/linter.code-snippets
- .vscode/syntax.code-snippets
- crates/squawk_linter/src/lib.rs
- crates/squawk_linter/src/rules/mod.rs
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test__begin_assume_transaction_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test__begin_repeated_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test__commit_repeated_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test__commit_with_assume_in_transaction_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__transaction_nesting__test__rollback_with_assume_in_transaction_err.snap
- crates/squawk_linter/src/rules/transaction_nesting.rs
- crates/squawk_syntax/src/ast/nodes.rs
- crates/xtask/src/new_lint.rs
> rule: add back transaction nesting to v2

- crates/cli/src/main.rs
basically let people know they should open a github issue!
> cli: add panic handler

- playground/src/main.tsx
> playground: update panic error screen

- .vscode/extensions/squawk-dev/README.md
- crates/squawk_linter/src/rules/prefer_robust_stmts.rs
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_robust_stmts__test__alter_column_set_not_null.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_robust_stmts__test__alter_table_drop_column_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_robust_stmts__test__disable_row_level_security_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_robust_stmts__test__double_add_after_drop_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_robust_stmts__test__enable_row_level_security_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_robust_stmts__test__enable_row_level_security_without_exists_check_err.snap
- playground/src/App.tsx
also update internal vscode extension readme
and fix typo in playground linter source name `tea` instead of `squawk`
> linter: improve prefer-robust-stmts error messages

- crates/squawk_parser/src/grammar.rs
- crates/squawk_parser/src/snapshots/squawk_parser__test__select_compound_union_select_ok.snap
- crates/squawk_parser/test_data/ok/select_compound_union_select.sql
we were handling
```sql
SELECT (
(SELECT c FROM t)
UNION
SELECT c FROM u
) LIMIT 1;
```
but not
```sql
SELECT (
(SELECT c FROM t)
UNION
(SELECT c FROM u)
) LIMIT 1;
```
related: https://github.com/sbdchd/squawk/issues/463
> parser: fix parsing nested compound select with parens

- README.md
- crates/squawk_parser/src/grammar.rs
- crates/squawk_parser/src/snapshots/squawk_parser__test__grant_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__revoke_ok.snap
- crates/squawk_parser/test_data/ok/grant.sql
- crates/squawk_parser/test_data/ok/revoke.sql
previously
```sql
GRANT ALL ON SEQUENCE public.s TO u;
```
wouldn't parse
managed to de-dupe some logic between revoke & grant
rel: https://github.com/sbdchd/squawk/issues/466
> parser: fix parsing grant / revoke with schema specified names

- CHANGELOG.md
- crates/squawk_parser/src/grammar.rs
- crates/squawk_parser/src/snapshots/squawk_parser__test__create_view_extra_parens_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__delete_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__merge_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__merge_pg17_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__misc_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__select_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__values_ok.snap
- crates/squawk_parser/test_data/ok/create_view_extra_parens.sql
> fix parsing `create view` with nested parens

- crates/squawk/src/github.rs
- crates/squawk_github/src/lib.rs
Closes #476
When searching for an existing comment to overwrite, check the body of each comment to see if it includes the expected header. This should prevent Squawk from accidentally overwriting comments generated by other GHAs.
> Check if existing comment contains "Squawk Report" header.

- crates/squawk_parser/src/grammar.rs
- crates/squawk_parser/src/snapshots/squawk_parser__test__alter_table_ok.snap
- crates/squawk_parser/src/snapshots/squawk_parser__test__create_table_ok.snap
- crates/squawk_parser/test_data/ok/alter_table.sql
- crates/squawk_parser/test_data/ok/create_table.sql
able to de-dupe some stuff!
related: https://github.com/sbdchd/squawk/issues/479
> parser: fix parsing table constraint fk actions

- crates/squawk_linter/src/rules/adding_field_with_default.rs
- crates/squawk_linter/src/rules/adding_foreign_key_constraint.rs
- crates/squawk_linter/src/rules/adding_not_null_field.rs
- crates/squawk_linter/src/rules/adding_primary_key_constraint.rs
- crates/squawk_linter/src/rules/adding_required_field.rs
- crates/squawk_linter/src/rules/ban_alter_domain_with_add_constraint.rs
- crates/squawk_linter/src/rules/ban_concurrent_index_creation_in_transaction.rs
- crates/squawk_linter/src/rules/ban_create_domain_with_constraint.rs
- crates/squawk_linter/src/rules/ban_drop_column.rs
- crates/squawk_linter/src/rules/ban_drop_database.rs
- crates/squawk_linter/src/rules/ban_drop_not_null.rs
- crates/squawk_linter/src/rules/ban_drop_table.rs
- crates/squawk_linter/src/rules/ban_truncate_cascade.rs
- crates/squawk_linter/src/rules/changing_column_type.rs
- crates/squawk_linter/src/rules/constraint_missing_not_valid.rs
- crates/squawk_linter/src/rules/disallow_unique_constraint.rs
- crates/squawk_linter/src/rules/prefer_robust_stmts.rs
- crates/squawk_linter/src/rules/renaming_column.rs
- crates/squawk_linter/src/rules/renaming_table.rs
- crates/squawk_linter/src/rules/require_concurrent_index_creation.rs
- crates/squawk_linter/src/rules/require_concurrent_index_deletion.rs
- crates/squawk_linter/src/rules/transaction_nesting.rs
- crates/squawk_linter/src/visitors.rs
- crates/squawk_syntax/src/ast/nodes.rs
- crates/squawk_syntax/src/ast/traits.rs
- crates/squawk_syntax/src/lib.rs
- crates/xtask/src/new_rule.rs
working on ungrammar and this is more descriptive, rust-analyzer uses Item, but all top level things in postgres are statements
> syntax: rename top level Item enum to Stmt

- crates/squawk_parser/src/syntax_kind.rs
- crates/squawk_parser/tests/snapshots/tests__listen_ok.snap
- crates/squawk_parser/tests/snapshots/tests__notify_ok.snap
- crates/squawk_parser/tests/snapshots/tests__unlisten_ok.snap
- crates/xtask/src/generate_keywords.rs
- postgres/kwlist.h
ran:
```sh
cargo xtask sync-kwlist
cargo xtask generate-keywords
cargo insta test --accept
```
> parser: bump kwlish.h to latest

- crates/squawk/src/debug.rs
- crates/squawk/src/reporter.rs
- crates/squawk/src/snapshots/squawk__reporter__test_reporter__display_violations_tty.snap
We were showing warning for everything and then using the error level for highlighting the error.
Now we set the level correctly!
> cli: display syntax errors as errors, not warnings part 2

- crates/squawk_linter/src/ignore.rs
- crates/squawk_linter/src/lib.rs
rel: https://github.com/sbdchd/squawk/issues/508
> linter: fix typo in PreferTimestampTz rule name

- crates/squawk_linter/src/rules/adding_not_null_field.rs
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_not_null_field__test__regression_gh_issue_519.snap
I think the changes from https://github.com/sbdchd/squawk/pull/412 / https://github.com/sbdchd/squawk/commit/360e3ee53edddfcfd63d0944699c7c7ab31ab7f3 didn't make it into the v2 codebase.
rel: https://github.com/sbdchd/squawk/issues/519
> linter: fix regression in adding_not_null_field related to v2 rewrite

- CHANGELOG.md
- Cargo.lock
- crates/squawk/Cargo.toml
- flake.nix
- package.json
rel: https://github.com/sbdchd/squawk/issues/519
> release: 2.11.0

- crates/squawk_parser/src/generated/syntax_kind.rs
- crates/squawk_parser/src/grammar.rs
- crates/squawk_parser/tests/snapshots/tests__create_view_extra_parens_ok.snap
- crates/squawk_parser/tests/snapshots/tests__delete_ok.snap
- crates/squawk_parser/tests/snapshots/tests__explain_ok.snap
- crates/squawk_parser/tests/snapshots/tests__merge_ok.snap
- crates/squawk_parser/tests/snapshots/tests__merge_pg17_ok.snap
- crates/squawk_parser/tests/snapshots/tests__misc_ok.snap
- crates/squawk_parser/tests/snapshots/tests__precedence_ok.snap
- crates/squawk_parser/tests/snapshots/tests__regression_suite_errors.snap
- crates/squawk_parser/tests/snapshots/tests__regression_xml.snap
- crates/squawk_parser/tests/snapshots/tests__select_ok.snap
- crates/squawk_parser/tests/snapshots/tests__values_ok.snap
- crates/squawk_syntax/src/ast/generated/nodes.rs
- crates/squawk_syntax/src/postgresql.ungram
We weren't parsing `xmltable` at all!
> parser: fix xmltable

- crates/squawk_parser/src/grammar.rs
- crates/squawk_parser/tests/data/ok/precedence.sql
- crates/squawk_parser/tests/snapshots/tests__precedence_ok.snap
- crates/squawk_parser/tests/snapshots/tests__select_compound_union_select_ok.snap
These now parse the same precedence wise:
```sql
SELECT foo UNION SELECT bar ORDER BY baz;
-- equal to:
(SELECT foo UNION SELECT bar) ORDER BY baz;
```
> parser: fix select precedence for trailing clauses

- .github/workflows/rust.yml
trying to de-dupe stuff to prep for more builds for vscode
> internal: refactor ci build to use matrix

- crates/squawk/src/main.rs
- crates/squawk_server/src/lib.rs
- docs/docs/syntax-error.md
- docs/sidebars.js
- squawk-vscode/package.json
- squawk-vscode/src/extension.ts
also:
- add missing docs page for syntax errors
- clear diagnostics on file close -- fixes stale diagnostics when switching file type from sql to plain text
> vscode: add status bar item to show server logs

- crates/squawk/src/main.rs
- squawk-vscode/eslint.config.mjs
- squawk-vscode/package.json
- squawk-vscode/src/extension.ts
also update the status bar to show when the server is stopped
> vscode: add start & stop server commands

- crates/squawk_server/src/lib.rs
- crates/squawk_server/src/lsp_utils.rs
- squawk-vscode/src/extension.ts
now we're storing the document state in memory on the server and doing incremental sync.
also cleanup the extension a bit so focus is kept when opening the syntax tree or the tokens
> server: incremental sync

- crates/squawk_linter/src/ignore.rs
- crates/squawk_linter/src/ignore_index.rs
- squawk-vscode/package.json
```sql
-- squawk-ignore-file
```
will ignore all rules for the file
```sql
-- squawk-ignore-file prefer-robust-stmts
```
will ignore a specific rule for the file
and
```sql
-- squawk-ignore prefer-robust-stmts
```
still ignores the rule on the following line
> linter: add file level ignores for rule violations

- crates/squawk_linter/src/rules/prefer_identity.rs
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__prefer_identity__test__err.snap
- crates/squawk_linter/src/visitors.rs
Keywords in PostgreSQL are always case-insensitive[1], therefore `BIGSERIAL` and `BiGsErIaL` types should be considered the same as `bigserial`.
[1] https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
> linter: detect invalid uppercase types

- crates/squawk_server/src/lib.rs
also fix filtering of diagnostics so we exclude diagnostics made by other language servers / extensions
> server: add quick fix to open documentation for rule violation

- crates/squawk/src/github.rs
- crates/squawk/src/main.rs
- crates/squawk_github/src/actions.rs
- crates/squawk_github/src/app.rs
- crates/squawk_github/src/lib.rs
fixes #609
NOTE: I haven't tested this yet, what's the best way of doing that? (And are we fine with taking the URL verbatim? This should be fine I think?).
(this goes along with https://github.com/sbdchd/squawk-action/pull/30)
> github: support overriding api url

- crates/squawk_linter/src/rules/adding_field_with_default.rs
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test__arbitrary_func_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test__default_random_with_args_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test__default_uuid_error.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test__default_uuid_error_multi_stmt.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test__default_volatile_func_err.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test__docs_example_error_on_pg_11.snap
- crates/squawk_linter/src/rules/snapshots/squawk_linter__rules__adding_field_with_default__test__generated_stored_err.snap
- crates/squawk_linter/src/test_utils.rs
> Add Postgres version check for adding field with default

- crates/squawk/src/main.rs
- docs/docs/cli.md
Currently, `squawk` exits with failure when the provided path pattern does not match any file.
This behavior can be unexpected, specifically when `squawk` is given the instruction to ignore files (via `excluded_paths `) and thus does not find any file to work on.
See issues https://github.com/sbdchd/squawk/issues/387 and https://github.com/sbdchd/squawk/issues/363 for more details.
This PR adds the option `--no-error-on-unmatched-pattern`, which causes the exit code to be `0` in cases mentioned above. `squawk` will still print the message stating that no files were found with the given pattern, which should help debugging cases where this may be unexpected.
> feat: add no-error-on-unmatched-pattern option

- crates/squawk_github/src/actions.rs
- crates/squawk_github/src/app.rs
- s/update-version
for some reason github started blocking calls, maybe related to the http tls change?
adding a user agent worked.
rel: https://github.com/sbdchd/squawk-action/issues/31
> github: fix calling API erroring

- Cargo.lock
- Cargo.toml
- PLAN.md
- crates/squawk/Cargo.toml
- crates/squawk/src/github.rs
- crates/squawk_github/Cargo.toml
- crates/squawk_lexer/Cargo.toml
- crates/squawk_linter/Cargo.toml
- crates/squawk_linter/src/lib.rs
- crates/squawk_linter/src/rules/adding_field_with_default.rs
- crates/squawk_linter/src/rules/ban_char_field.rs
- crates/squawk_linter/src/rules/constraint_missing_not_valid.rs
- crates/squawk_linter/src/rules/disallow_unique_constraint.rs
- crates/squawk_linter/src/rules/prefer_bigint_over_int.rs
- crates/squawk_linter/src/rules/prefer_bigint_over_smallint.rs
- crates/squawk_linter/src/rules/prefer_identity.rs
- crates/squawk_linter/src/rules/prefer_robust_stmts.rs
- crates/squawk_linter/src/rules/prefer_text_field.rs
- crates/squawk_linter/src/rules/prefer_timestamptz.rs
- crates/squawk_linter/src/rules/require_concurrent_index_creation.rs
- crates/squawk_linter/src/visitors.rs
- crates/squawk_parser/Cargo.toml
- crates/squawk_server/Cargo.toml
- crates/squawk_syntax/Cargo.toml
- crates/squawk_syntax/src/identifier.rs
- crates/squawk_syntax/src/lib.rs
- crates/squawk_wasm/Cargo.toml
- crates/xtask/Cargo.toml
- s/check-version
- s/update-version
also change how we version the crates
> squawk_syntax: refactor identifier out of squawk_linter

- Cargo.lock
- Cargo.toml
- crates/squawk/src/debug.rs
- crates/squawk/src/github.rs
- crates/squawk/src/reporter.rs
- crates/squawk/src/snapshots/squawk__github__test_github_comment__generating_comment_multiple_files.snap
- crates/squawk/src/snapshots/squawk__reporter__test_reporter__display_violations_tty.snap
- crates/squawk/src/snapshots/squawk__reporter__test_reporter__display_violations_tty_and_github_annotations.snap
> cli: upgrade annotate-snippets to latest

- .github/workflows/rust.yml
- Cargo.toml
- rust-toolchain.toml
- s/update-version
rel: https://github.com/sbdchd/squawk/issues/333#issuecomment-3314972239
> internal: bump rust to 1.90.0

- PLAN.md
- crates/squawk/src/config.rs
- crates/squawk/src/snapshots/squawk__config__test_config__load_excluded_rules_with_alias.snap
- crates/squawk_linter/src/lib.rs
https://github.com/sbdchd/squawk/issues/667
> cli: fix parsing of rule name aliases i.e., prefer-timestamptz
